name: CICD
on:
  [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v4

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: gusarod7.beget.tech
            username: gusarod7
            password: ${{ secrets.PASSWORD }}
            script: |
                cd gusarod7.beget.tech/public_html
                git pull origin master