name: CICD
on:
  [push]
jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: gusarod7.beget.tech
            username: gusarod7
            key: ${{ secrets.PASSWORD }}
            script: |
                cd gusarod7.beget.tech/public_html
                git pull origin master